DROP DATABASE IF EXISTS zombee;
CREATE DATABASE IF NOT EXISTS zombee;
USE zombee;

CREATE TABLE orgs(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  short_name VARCHAR(255) NOT NULL,
  long_name TEXT NOT NULL,
  website VARCHAR(255),
  image_id INT UNSIGNED,
  created_date DATETIME NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  modified_date TIMESTAMP NOT NULL,
  modified_by INT UNSIGNED NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE
);

CREATE TABLE contacts(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  org_id INT UNSIGNED NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  middle_name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  skype VARCHAR(255),
  website VARCHAR(255),
  linkedin VARCHAR(255),
  facebook VARCHAR(255),
  twitter VARCHAR(255),
  googleplus VARCHAR(255),
  current_title VARCHAR(255),
  current_org INT UNSIGNED,
  former_title VARCHAR(255),
  former_org INT UNSIGNED,
  image_id INT UNSIGNED,
  created_date DATETIME NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  modified_date TIMESTAMP NOT NULL,
  modified_by INT UNSIGNED NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE
);

CREATE TABLE images(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(255) NOT NULL,
  width INT UNSIGNED NOT NULL,
  height INT UNSIGNED NOT NULL,
  resolution INT UNSIGNED NOT NULL,
  created_date DATETIME NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  modified_date TIMESTAMP NOT NULL,
  modified_by INT UNSIGNED NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE
);


